<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="AutoFixture.AutoMoq" Version="4.18.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samples.Adapter\Samples.Adapter.csproj" />
    <ProjectReference Include="..\Samples.Async.Progress\Samples.Async.Progress.csproj" />
    <ProjectReference Include="..\Samples.Async\Samples.Async.csproj" />
    <ProjectReference Include="..\Samples.Bridge\Samples.Bridge.csproj" />
    <ProjectReference Include="..\Samples.Builder\Samples.Builder.csproj" />
    <ProjectReference Include="..\Samples.Command\Samples.Command.csproj" />
    <ProjectReference Include="..\Samples.Composite\Samples.Composite.csproj" />
    <ProjectReference Include="..\Samples.Facade\Samples.Facade.csproj" />
    <ProjectReference Include="..\Samples.Factory\Samples.Factory.csproj" />
    <ProjectReference Include="..\Samples.Mediator\Samples.Mediator.csproj" />
    <ProjectReference Include="..\Samples.MessageBroker\Samples.MessageBroker.csproj" />
    <ProjectReference Include="..\Samples.NullObject\Samples.NullObject.csproj" />
    <ProjectReference Include="..\Samples.Observer\Samples.Observer.csproj" />
    <ProjectReference Include="..\Samples.Singleton\Samples.Singleton.csproj" />
    <ProjectReference Include="..\Samples.TemplateMethod\Samples.TemplateMethod.csproj" />
  </ItemGroup>

</Project>
